[package]
name = "db_client"
version = "0.1.0"
edition = "2021"

[dependencies]
db_common = { path = "../db_common" }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
 serde = { version = "1.0", features = ["derive"] }