[package]
name = "db_metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
db_common = { path = "../db_common" }
rocksdb = "0.22.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"